# Generated by Django 4.2.2 on 2023-06-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Course_Name',
            new_name='Category_Name',
        ),
    ]
